---
title: "Replication Test"
author: "Ito Hiroki"
date: today
execute:
  warning: false
  error: false
format: 
  html:
    code-fold: true
    embed-resources: true
---

# Setup
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(kableExtra)
library(gtExtras)
library(fixest)
library(cobalt)
```


```{r}
# df_raw <- haven::read_dta(here::here('01.data', 'ipeds_cleaned_final.dta'))
df_raw <- readr::read_csv(here::here('01.data', 'ipeds_cleaned_final.csv'))
df_main <- readr::read_csv(here::here('01.data', 'based_df.csv'))

df_stata <- readr::read_csv(here::here('01.data', 'stata', 'test_IPEDS_Analysis_Figure.csv'))
```

# Clean Data Set
```{r}
df_based <- df_raw |> 
  dplyr::filter(dplyr::between(year, 1991, 2010),
                year != 1994) |> 
  tidyr::drop_na(faculty, instatetuition, revenue, costs) |> 
  tidyr::complete(unitid, year) # 年によるサンプル数のバランスを調節

# detect unitid that contains NA value in "gradrate4yr"
list_na_gradrate4yr <- df_based |> 
  dplyr::filter(is.na(gradrate4yr)) |> 
  dplyr::distinct(unitid) |> 
  dplyr::pull()

df_based <- df_based |> 
  dplyr::filter(!unitid %in% list_na_gradrate4yr) 


df_based <- df_based |> 
  tidyr::drop_na(gradrate4yr, gradrate6yr) |> 
  dplyr::mutate(
    mandate = dplyr::if_else(fips %in% c(13, 27, 38, 39, 48, 49), 1, 0)
  ) |> 
  dplyr::mutate(
    changer = dplyr::if_else(!is.na(yearstosem), 1, 0),
      # womengradrate4yr_mod = (w_4yrgrads/w_cohortsize), # womangradrate4yrと同じ値
      # mengradrate4yr_mod = (m_4yrgrads/m_cohortsize), # mengradrate4yrと同じ値
      # whitegradrate4yr_mod = (white_4yrgrads/white_cohortsize),
      per_white=(white_cohortsize/totcohortsize),
      per_urm=(urm_cohortsize/totcohortsize),
      per_male=(m_cohortsize/totcohortsize),
      per_fem=(w_cohortsize/totcohortsize)
  ) 
# write.csv(df_based, file = here::here('01.data', 'based_df.csv'), fileEncoding = 'cp932', row.names = FALSE)
```
# Figures and Tables

## Figure 1
```{r}

df_plot_based <- df_based |> 
  dplyr::summarise(
    mean = mean(gradrate4yr, na.rm = TRUE),
    .by = year
  )


ggplot(df_plot_based, aes(x = year, y = mean))+
  # geom_point() +
  geom_line() +
  theme_bw() +
  scale_y_continuous(
    limits = c(0.25, 0.45),
    breaks = seq(0.25, 0.45, 0.05)
  ) +
  labs(
    title = 'Fraction of Four-Year Graduation Rates'
  )
```

## Figure 1 
```{r}
df_plot_based <- df_based |> 
  dplyr::summarise(
    semester_size = sum(semester2),
    total_size = dplyr::n(),
    .by = c(year)
  ) |> 
  dplyr::mutate(
    percent = semester_size / total_size
  )

df_plot_based

ggplot(df_plot_based, aes(x = year, y = percent)) +
  geom_line() +
  theme_bw() +
  scale_y_continuous(
    limits = c(0.80, 1),
    breaks = seq(0.80, 1, 0.05)
  ) +
  labs(
    title = 'Fraction of Schools on Semesters'
  )
```

```{r}
df_grad_rate <- df_based |> 
  dplyr::summarise(
    mean = mean(gradrate4yr, na.rm = TRUE),
    .by = year
  ) |> 
  dplyr::mutate(
    adjust_mean = mean + 0.55
  )

df_semester_rate <- df_based |> 
  dplyr::summarise(
    semester_size = sum(semester2),
    total_size = dplyr::n(),
    .by = c(year)
  ) |> 
  dplyr::mutate(
    percent = semester_size / total_size
  )


ggplot() +
  geom_line(data = df_grad_rate, aes(x = year, y = adjust_mean), linetype = 'longdash') +
  geom_line(data = df_semester_rate, aes(x = year, y = percent), linetype = 'solid') +
  theme_bw() +
  scale_y_continuous(
    limits = c(0.80, 1),
    breaks = seq(0.80, 1, 0.05)
  )
  



```
## scatter plots


## Table 1 : Descriptive statistics
```{r}

# df_modified <- df_based |> 
df_modified <- df_stata |> 
  dplyr::select(
    unitid,
    year,
    semester2,
    quarter2,
    totcohortsize,
    # m_cohortsize,
    # w_cohortsize,
    gradrate4yr,
    gradrate6yr,
    mengradrate4yr,
    mengradrate6yr,
    womengradrate4yr,
    womengradrate6yr,
    public,
    faculty,
    instatetuition
  ) |> 
  tidyr::pivot_longer(
    cols = -c(unitid, year),
    names_to = 'category',
    values_to = 'value'
  )

df_table_based <- df_modified |>
  dplyr::filter(
    !category %in% c("semester2", "quarter2")
  ) |> 
  dplyr::reframe(
    mean = round(mean(value, na.rm = TRUE), digits = 2),
    sd = round(sd(value, na.rm = TRUE), digits = 2),
    # grad_rate_4yr = mean(gradrate4yr),
    # grad_rate_4yr_m = mean(per_male),
    # grad_rate_4yr_w = mean(per_fem),
    # grad_rate_6yr = mean(gradrate6yr),
    # grad_rate_6yr_m = mean(mengradrate6yr),
    # grad_rate_6yr_w = mean(womengradrate6yr),
    # # Semester_rate = jj
    # Observations = dplyr::n(),
    .by = category
  )
```

### Descriptive Stats
- 一部、元の論文と異なるが概ね整合的
```{r}

df_table_based |> 
  kbl(format = "html", booktabs = TRUE,
      table.attr = 'data-quarto-disable-processing="true"') |> 
  kable_styling(full_width = FALSE) 
```



## Figure 2
- 全く違う、記述統計が概ね合っているので、推定式や重み付けの問題か
```{r}
df_first_year <- df_based |> 
  dplyr::filter(
    changer == 1,
    semester2 == 1
  ) |> 
  summarise(
    first_year = min(year),
    .by = unitid
  ) |> 
  dplyr::distinct()


df_ols_based <- df_based |> 
  dplyr::left_join(df_first_year, by = 'unitid') |> 
  dplyr::relocate(first_year, .after = year) |> 
  dplyr::mutate(
    relative_year = year - first_year,
    relative_year = dplyr::if_else(is.na(relative_year), -1000, relative_year),
    .after = first_year) |> 
  dplyr::filter(between(relative_year, -10, 10)) |> 
  dplyr::mutate(
    # dplyr::across(c(group1, group2), ~replace_na(.x, 0)),
    per_white=(white_cohortsize/totcohortsize),
    per_urm=(urm_cohortsize/totcohortsize),
    per_fem=(w_cohortsize/totcohortsize)
  )



twfe <- feols(fml = gradrate4yr ~ instatetuition + costs + faculty + i(relative_year, ref = c(-4, -1000)) + year:unitid | year + unitid, data = df_ols_based)

# colnames(df_ols_based)
etable(twfe)

iplot(twfe)


```

## not inclucded
```{r}

df_table3_based <- df_based |> 
  dplyr::left_join(df_first_year, by = 'unitid') |> 
  dplyr::relocate(first_year, .after = year) |> 
  dplyr::mutate(
    relative_year = year - first_year,
    group1 = dplyr::if_else(dplyr::between(relative_year, -3, -1) == TRUE, 1, 0),
    group2 = dplyr::if_else(dplyr::between(relative_year, 0, 100) == TRUE, 1, 0),
    .after = year
    )

```


## Table 3
- 重み付けの問題からか推定結果が合わない。（式が異なるのか、吹原さんのSTATA環境で試したい。）
```{r}

df_table3_based <- df_based |> 
  dplyr::left_join(df_first_year, by = 'unitid') |> 
  dplyr::relocate(first_year, .after = year) |> 
  dplyr::mutate(
    relative_year = year - first_year,
    group1 = dplyr::if_else(dplyr::between(relative_year, -3, -1) == TRUE, 1, 0),
    group2 = dplyr::if_else(dplyr::between(relative_year, 0, 100) == TRUE, 1, 0),
    .after = year
    ) |> 
  dplyr::mutate(
    dplyr::across(c(group1, group2), ~replace_na(.x, 0)),
    per_white=(white_cohortsize/totcohortsize),
    per_urm=(urm_cohortsize/totcohortsize),
    per_fem=(w_cohortsize/totcohortsize)
  )
  

df_cohortsize = df_table3_based |>
  dplyr::select(
    unitid,
    # totcohortsize,
    meansize
  ) |> 
  dplyr::distinct() |> 
  dplyr::mutate(
    weight = meansize / sum(meansize, na.rm = TRUE),
    weight_unit = weight / 19
  )
  
  # dplyr::summarise(
  #   cohortsize = dplyr::n(),
  #   .by = relative_year
  # ) |>
  # tidyr::drop_na(relative_year) |>
  # dplyr::mutate(
  #   weight = cohortsize / sum(cohortsize)
  # )

df_table3_based_a <- df_table3_based |>
  dplyr::left_join(df_cohortsize, by = 'unitid') |>
  dplyr::select(
    gradrate4yr,
    gradrate6yr,
    group1,
    group2,
    year,
    relative_year,
    semester,
    unitid,
    weight,
    weight_unit,
    instatetuition,
    costs,
    faculty,
    per_white,
    per_urm,
    per_fem,
    totcohortsize
    # meansize
    ) 
  # dplyr::mutate(
  #   weight = meansize / sum(meansize, na.rm = TRUE)
  # ) 
  # dplyr::filter(
  #   relative_year >= -10, 
  #   relative_year <= 10 
  # )

df_table3_based |> 
  dplyr::distinct(unitid) |> 
  nrow()

fixest::feols(gradrate4yr ~ group1 + group2 | unitid + year,
              data = df_table3_based_a,
              # weights = ~ meansize,
              # weights = ~ weight,
              cluster = 'unitid') |>
  etable()


# fixest::feols(gradrate4yr ~ group1 + group2 + instatetuition + costs + faculty + per_white + per_urm + per_fem | year + unitid,
#               data = df_table3_based,
#               cluster = 'unitid') |>
#   etable()
# 
# estimatr::lm_robust(gradrate4yr ~ group1 + group2,
#                     fixed_effects = ~ year + unitid,
#                     # weights = meansize,
#                     data = df_table3_based) |> 
#   modelsummary::msummary()
  
```

# 宿題の回帰式
## （１） 
$$ Y_{it} =  \beta_0 + \beta_1Semester_{it} + \varepsilon_{it}$$
```{r}
estimatr::lm_robust(gradrate4yr ~ semester,
                    data = df_table3_based) |> 
  modelsummary::msummary()
```
## 共変量あり（２）
$$ Y_{it} =  \beta_0 + \beta_1Semester_{it} + \gamma \textbf{\textit{X}}_{it} + \varepsilon_{it}$$
- 論文ではinstatetuitionを共変量に加えているが、中間経路の問題があるためなぜ含めているのか疑問
```{r}
estimatr::lm_robust(gradrate4yr ~ semester + instatetuition + costs + faculty + per_white + per_urm + per_fem,
                    data = df_table3_based) |> 
  modelsummary::msummary()
```








