---
title: "Problem Set 2"
# author: "古川知志雄, 伊藤弘紀, 吹原ゆうや"
date: today 
format: 
  html: 
    embed-resources: true
    self-contained: true
execute: 
  echo: false
---
    
## 提出期限
- 2024年2月6日（火曜）17:00


# 3. 分析課題

## データの分析

##### 注意事項
- (Adv.)が書かれている場合は、上級問題のため必ず解く必要はない\
- 参考資料に論文中の図表を引用しているが、その通りに作成する必要はなく、自分なりに工夫すること

\

#### (a) 記述統計
###### 1. 問題背景などを知る上で役に立つ記述統計を作成し、内容について議論しなさい
- 参考：\
　論文Table 1　

###### 2. 4年卒業率の平均推移を計算し、図で示しなさい
- 参考：\
　論文Figure 1

###### 3. semester導入率を計算し、図で示しなさい
- 参考：\
　論文Figure 1

　**注意：問2, 問3のプロットは別々の図として作成することを推奨する**

###### 4. **変数に処理を加えた上**で、以下の散布図を作成しなさい。また、重要だと考える結果について議論しなさい

1. 4年卒業率と男子学生比率
2. 4年卒業率と女子学生比率
3. 4年卒業率と白人学生割合
4. 4年卒業率と年間運営コスト(costs)
5. 4年卒業率と学費(instatetuition)

- 作成の際には関数を作成することを強く推奨する
- ヒント: \
　"rlang" package (enquo関数, sym関数)\
　使い方については、以下のHPが参考になる \
　[https://www.tidyverse.org/blog/2018/07/ggplot2-tidy-evaluation/#tidy-facets-with-vars](https://www.tidyverse.org/blog/2018/07/ggplot2-tidy-evaluation/#tidy-facets-with-vars)\
　[https://ggplot2.tidyverse.org/reference/tidyeval.html](https://ggplot2.tidyverse.org/reference/tidyeval.html)

\

###### 5. (Adv.) semester制の導入と共変量の関係を分析しなさい
- 参考：\
　論文Table2に関連する箇所を読むこと\
　追加で配布したSTATAコードを参照し、回帰式を考える\
　該当箇所：85行目以下 `***Table 2: Effect of Switching to ~`

\

#### (b) 回帰分析
###### 1. 以下の3つの変数を作成しなさい
- "yearofsem"
    - semester制が導入された年
- "yearstosem"
    - semeter制導入からの相対年数
        - 例：2000年にsemester制が導入された場合、1997年は-3、1998年は-2、1999年は-1、2000年は0、2001年は1、2002年は2、2003年は3, ...
- "treated"
    - "yearstosem"が0以上の時に1をとるダミー変数  

###### 2. 以下の式を推定し、結果について議論しなさい
- $s$：大学、$k$：相対年数(yearstosem)
$$ 
Y_{sk} = \beta_0 + \beta_1 \text{treated}_{sk} + \varepsilon_{sk} \label{base_eq}\tag{1}
$$  


###### 3. 数式 (1) の問題点を指摘しなさい

- 参考：\
　論文セクション2, B:「Empirical Framework: Institution Level」\
　[11 因果推論の共変量制御アプローチ](https://chishio318.github.io/statistics/%E5%9B%A0%E6%9E%9C%E6%8E%A8%E8%AB%96%E3%81%AE%E5%85%B1%E5%A4%89%E9%87%8F%E5%88%B6%E5%BE%A1%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81.html)\
　[12 因果推論の実験的アプローチ](https://chishio318.github.io/statistics/%E5%9B%A0%E6%9E%9C%E6%8E%A8%E8%AB%96%E3%81%AE%E5%AE%9F%E9%A8%93%E7%9A%84%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81.html)  

\


###### 4. (Adv.) 問3.で指摘した点に対する改善が加えられている回帰式を考えなさい。その推定結果を議論しなさい
- 必ずしも全ての問題点を考慮する必要はない
\


###### 5. (Adv.) 介入前期間において、トリートメント群とコントロール群のトレンドが平行かどうかを検証しなさい
- ヒント：\
　Event Study Design　(Event Studyにはいくつか意味があるため注意)
- 参考：\
　論文Figure 2, Panel A\
　[Causal Inference : The Mixtape](https://mixtape.scunning.com/09-difference_in_differences#a-redundant-rant-about-parallel-pre-treatment-dd-coefficients-because-im-worried-one-was-not-enough)\
　[11 因果推論の共変量制御アプローチ](https://chishio318.github.io/statistics/%E5%9B%A0%E6%9E%9C%E6%8E%A8%E8%AB%96%E3%81%AE%E5%85%B1%E5%A4%89%E9%87%8F%E5%88%B6%E5%BE%A1%E3%82%A2%E3%83%97%E3%83%AD%E3%83%BC%E3%83%81.html)

\
